### PR TITLE
fixes for issue #3 and issue #4

### PR DESCRIPTION
**Pull request by markheger**
delivery for issue #4

### CODE REVIEW

**Comment by markheger** [comment]
delivery for issue #3

**Comment by chanskw** [comment]
@cancilla Can you please review this pull request and pull this in?

**Comment by markheger** [comment]
@chanskw @cancilla Is there any update on this? Samples are not usable at the moment.

**Comment by cancilla** [comment]
@markheger Why change the info.xml to be specifically dependent on v2.6.3 of the network toolkit? Any changes made to the toolkit will ultimately cause these samples to not compile.

**Comment by cancilla** [comment]
@markheger Actually, if you look at the latest version of the network toolkit on GitHub, it's been bumped to v3.0.4. The samples should be tested against v3.x of the network toolkit and if everything works, update the info.xml to support both v2 and v3 ( i.e. [2.0.0, 4.0.0) ).

**Comment by markheger** [comment]
yes, I have tested the samples and with the changes of this pull request the samples work fine with the latest network toolkit. As you know the build.xml in the samples loads always the latest network toolkit from Github.Therefore no changes in the samples has the result that they do not compile at the moment.
I agree, that the info.xml could be updated to [2.0.0, 4.0.0)

**Pull request merged**
